version: "3.7"
services:
  grafana:
    image: grafana/grafana-oss
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
volumes:
  grafana_data:
